# This file was generated by GoReleaser. DO NOT EDIT.
cask "hotline" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "db0d23d2b30264d1fdf6c3a1e0574359a88a23bc230e16cc9ba338307c1ee4c9"
      url "https://github.com/1broseidon/hotline/releases/download/v#{version}/hotline_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "82326d41636fc94d6e6fdbc7a555c10ddacd2944703fa0e730c4ddd39ffe9765"
      url "https://github.com/1broseidon/hotline/releases/download/v#{version}/hotline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c39e3eb43c4c114725bd465795a85908bb75853518faead3a639079ad2be5b2c"
      url "https://github.com/1broseidon/hotline/releases/download/v#{version}/hotline_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c7fbf36c723b9925a3cbbf5105c7533de978217c1405d14695c681ba4e9f411a"
      url "https://github.com/1broseidon/hotline/releases/download/v#{version}/hotline_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hotline"
  desc "Messaging channel for Claude Code. Talk to your sessions like texting a friend."
  homepage "https://hotline.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hotline"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hotline"]
    end
  end

  # No zap stanza required

end
