# This file was generated by GoReleaser. DO NOT EDIT.
cask "oa" do
  name "oa"
  desc "Config-driven multi-agent CLI with a normalized interface"
  homepage "https://github.com/1broseidon/oneagent"
  version "0.10.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oa"

  on_macos do
    on_intel do
      url "https://github.com/1broseidon/oneagent/releases/download/v#{version}/oa_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/1broseidon/oneagent/"
      sha256 "110f448fe2e6be4ee74c5ae4d82a8d6136e2aa6222d92ae469164e6397b93d80"
    end
    on_arm do
      url "https://github.com/1broseidon/oneagent/releases/download/v#{version}/oa_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/1broseidon/oneagent/"
      sha256 "1c8f5498339d0244dc512d74413dd09c7da881c3a2be43766e1ac7dfbd02a2d1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/1broseidon/oneagent/releases/download/v#{version}/oa_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/1broseidon/oneagent/"
      sha256 "ed2ea628eb9692c2e8da6ce910fa3c376ec2b9238d62e2c577f1b355eca083f1"
    end
    on_arm do
      url "https://github.com/1broseidon/oneagent/releases/download/v#{version}/oa_#{version}_linux_arm64.tar.gz",
        verified: "github.com/1broseidon/oneagent/"
      sha256 "3bcbf5f08966f112ba801c334392bfd5fd3b666b4e8aa7c9346dd48910347495"
    end
  end

  # No zap stanza required
end
