# This file was generated by GoReleaser. DO NOT EDIT.
cask "oa" do
  name "oa"
  desc "Config-driven multi-agent CLI with a normalized interface"
  homepage "https://github.com/1broseidon/oneagent"
  version "0.10.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oa"

  on_macos do
    on_intel do
      url "https://github.com/1broseidon/oneagent/releases/download/v#{version}/oa_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/1broseidon/oneagent/"
      sha256 "3c016b51919a7eaf836c71a0200f7b03a325369e809ed7cba57bccc2eae027ad"
    end
    on_arm do
      url "https://github.com/1broseidon/oneagent/releases/download/v#{version}/oa_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/1broseidon/oneagent/"
      sha256 "eb3772671fc96ded497dff65a69e1d66321bdb51e49ea6345ecf8a362bdc1c45"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/1broseidon/oneagent/releases/download/v#{version}/oa_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/1broseidon/oneagent/"
      sha256 "30df1942016bc07ed2e0256ee096e7d2c0afdd400560d712a7b657b8ab86e39d"
    end
    on_arm do
      url "https://github.com/1broseidon/oneagent/releases/download/v#{version}/oa_#{version}_linux_arm64.tar.gz",
        verified: "github.com/1broseidon/oneagent/"
      sha256 "ee3fddb771ba57599b1907b6d38a1623e5d8efe0035ae727606933c65fb112fd"
    end
  end

  # No zap stanza required
end
