# This file was generated by GoReleaser. DO NOT EDIT.
cask "oa" do
  name "oa"
  desc "Config-driven multi-agent CLI with a normalized interface"
  homepage "https://github.com/1broseidon/oneagent"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oa"

  on_macos do
    on_intel do
      url "https://github.com/1broseidon/oneagent/releases/download/v#{version}/oa_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/1broseidon/oneagent/"
      sha256 "665451237a5192f18d70ad725f2dc5b06948447a5b0437a4879bc064e3b241f4"
    end
    on_arm do
      url "https://github.com/1broseidon/oneagent/releases/download/v#{version}/oa_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/1broseidon/oneagent/"
      sha256 "d2f1b12288dcf6ea886e6451b7f23c5fda67de501d2d39c1a81046b142d6c033"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/1broseidon/oneagent/releases/download/v#{version}/oa_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/1broseidon/oneagent/"
      sha256 "5e9be0c0b2200cc327d9f6a67ffa869bd38fbf17106f2f1dba4be76c8f5845fd"
    end
    on_arm do
      url "https://github.com/1broseidon/oneagent/releases/download/v#{version}/oa_#{version}_linux_arm64.tar.gz",
        verified: "github.com/1broseidon/oneagent/"
      sha256 "fe2dfd38b996cec9a3d6ba6e17364383882c29e3aa17d8cc8a74b64162ccfe3a"
    end
  end

  # No zap stanza required
end
