# This file was generated by GoReleaser. DO NOT EDIT.
cask "promptext" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-d", "com.apple.quarantine", "#{staged_path}/promptext"],
                   sudo: false
  end

  name "promptext"
  desc "Smart code context extractor for AI assistants"
  homepage "https://github.com/1broseidon/promptext"
  version "0.5.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promptext"

  on_macos do
    on_intel do
      url "https://github.com/1broseidon/promptext/releases/download/v#{version}/promptext_Darwin_x86_64.tar.gz"
      sha256 "b2c192eb6e7917d78d06e325d4e8487ee92efcaa4f87560f1e324ae41284a102"
    end
    on_arm do
      url "https://github.com/1broseidon/promptext/releases/download/v#{version}/promptext_Darwin_arm64.tar.gz"
      sha256 "b0d708f29bf85cbd124c897c107423e303a3cf15e71d5f95b32ce7a301cdde5e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/1broseidon/promptext/releases/download/v#{version}/promptext_Linux_x86_64.tar.gz"
      sha256 "40af6258a536f831cdf1f72e6747a3d337b772ad6267b49c4c46bccd263d484e"
    end
    on_arm do
      url "https://github.com/1broseidon/promptext/releases/download/v#{version}/promptext_Linux_arm64.tar.gz"
      sha256 "667d01c610c1c1f3339f654654ef79abcace329a6efd957edb8f468ad0934059"
    end
  end

  # No zap stanza required
end
