# This file was generated by GoReleaser. DO NOT EDIT.
cask "promptext" do
  name "promptext"
  desc "Smart code context extractor for AI assistants"
  homepage "https://github.com/1broseidon/promptext"
  version "0.5.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prx"

  on_macos do
    on_intel do
      url "https://github.com/1broseidon/promptext/releases/download/v#{version}/promptext_#{version}_darwin_amd64.tar.gz"
      sha256 "0145efae8a4b6d8eefe9ea65b15c0047fdaaa00a0005ffd3495e5a7d6bb141e3"
    end
    on_arm do
      url "https://github.com/1broseidon/promptext/releases/download/v#{version}/promptext_#{version}_darwin_arm64.tar.gz"
      sha256 "645e4b6217e2213148d161507e1f6e4d1c8f1b5c10e19329c586a8db8de7696b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/1broseidon/promptext/releases/download/v#{version}/promptext_#{version}_linux_amd64.tar.gz"
      sha256 "b04215ef13878f2e91ed0b169963fc469710da8f46d923d1829d74e1de95dc0e"
    end
    on_arm do
      url "https://github.com/1broseidon/promptext/releases/download/v#{version}/promptext_#{version}_linux_arm64.tar.gz"
      sha256 "26cbec8fef25a72b87761bd27ab3d6612988b10fd152389a78bbb8d2b21cd822"
    end
  end

  # No zap stanza required
end
