# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghostmux < Formula
  desc "The tmux fleet navigator"
  homepage "https://github.com/1broseidon/ghostmux"
  version "0.3.1"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1broseidon/ghostmux/releases/download/v0.3.1/ghostmux_0.3.1_darwin_x86_64.tar.gz"
      sha256 "72b98e7f3cb740067a02f15692a7f7ba42e4c4e08c8bd5369b18789dc6ad37da"

      define_method(:install) do
        bin.install "ghostmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1broseidon/ghostmux/releases/download/v0.3.1/ghostmux_0.3.1_darwin_arm64.tar.gz"
      sha256 "7359e385d9952c7fb91d27c39da80dd1d132d06554ada49461d8fa47b6660010"

      define_method(:install) do
        bin.install "ghostmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/ghostmux/releases/download/v0.3.1/ghostmux_0.3.1_linux_x86_64.tar.gz"
      sha256 "c59b5dc03c1f05e78d3f200928e625fb4b5e02452c89b18260cba70b9f11bc14"
      define_method(:install) do
        bin.install "ghostmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/ghostmux/releases/download/v0.3.1/ghostmux_0.3.1_linux_arm64.tar.gz"
      sha256 "41a3faa5a1681362b4ba7c6b37f7c4d53d0a791b827a45975bc28fee4f40386c"
      define_method(:install) do
        bin.install "ghostmux"
      end
    end
  end
end
