# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghostmux < Formula
  desc "The tmux fleet navigator"
  homepage "https://github.com/1broseidon/ghostmux"
  version "0.3.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1broseidon/ghostmux/releases/download/v0.3.0/ghostmux_0.3.0_darwin_x86_64.tar.gz"
      sha256 "c9dbb340a499650559f8f02621f354b3e6119112a16e642f14cbbf508a3242ad"

      define_method(:install) do
        bin.install "ghostmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1broseidon/ghostmux/releases/download/v0.3.0/ghostmux_0.3.0_darwin_arm64.tar.gz"
      sha256 "2dd29177615525f84f5494af5ea4cdf97ce3215f2a9a3ed560654bf7b05b192b"

      define_method(:install) do
        bin.install "ghostmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/ghostmux/releases/download/v0.3.0/ghostmux_0.3.0_linux_x86_64.tar.gz"
      sha256 "c9bb09dc58656e3531b4f2de9f7363acbe92ada9647f3064371fbe3fa4030eb2"
      define_method(:install) do
        bin.install "ghostmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/ghostmux/releases/download/v0.3.0/ghostmux_0.3.0_linux_arm64.tar.gz"
      sha256 "5b00a924db252928643b1a0a0c2dcb2850984a6f2648a7ba3102ef579abbfb8b"
      define_method(:install) do
        bin.install "ghostmux"
      end
    end
  end
end
