# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hotline < Formula
  desc "Messaging channel for Claude Code. Talk to your sessions like texting a friend."
  homepage "https://github.com/1broseidon/hotline"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1broseidon/hotline/releases/download/v0.1.0/hotline_0.1.0_darwin_x86_64.tar.gz"
      sha256 "c719b8f0f051d94fd380ac51fe441983fdc4bdc439f2b09ec4f2898a5b21f7d8"

      define_method(:install) do
        bin.install "hotline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1broseidon/hotline/releases/download/v0.1.0/hotline_0.1.0_darwin_arm64.tar.gz"
      sha256 "d74781a88d8e1adbff9cc91f48ddcf72bd3c72db593963616cd6a2f812217180"

      define_method(:install) do
        bin.install "hotline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/hotline/releases/download/v0.1.0/hotline_0.1.0_linux_x86_64.tar.gz"
      sha256 "5a4680b997c63813692a5c7e024ff968347cbfae29afaf0c47268da8a7c11e54"
      define_method(:install) do
        bin.install "hotline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/hotline/releases/download/v0.1.0/hotline_0.1.0_linux_arm64.tar.gz"
      sha256 "875cb3714f617c2dbb49dc62ed128aec14c2abbb0d6f67ca4581fa574276fb33"
      define_method(:install) do
        bin.install "hotline"
      end
    end
  end

  test do
    system "#{bin}/hotline", "--help"
  end
end
