# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ketch < Formula
  desc "Fast web search and scrape CLI for agents"
  homepage "https://github.com/1broseidon/ketch"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1broseidon/ketch/releases/download/v0.9.1/ketch_0.9.1_darwin_x86_64.tar.gz"
      sha256 "37aed6c4460c3ed413c5c0901f6e51e0749ed46b974495e72e1e3938773cd328"

      define_method(:install) do
        bin.install "ketch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1broseidon/ketch/releases/download/v0.9.1/ketch_0.9.1_darwin_arm64.tar.gz"
      sha256 "3c1b87c2c3690b2a17e16a3d78b15ec855fa05b789deb01f8936baa54ab62e78"

      define_method(:install) do
        bin.install "ketch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/ketch/releases/download/v0.9.1/ketch_0.9.1_linux_x86_64.tar.gz"
      sha256 "44070f19eff3a61c39e42fe3fdcd2f686b390bb629dba82ab390814f5ccb2805"
      define_method(:install) do
        bin.install "ketch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/ketch/releases/download/v0.9.1/ketch_0.9.1_linux_arm64.tar.gz"
      sha256 "cea01417b1653f6e3f35f33cfa1eba81a1c6cf1a4d4975592f908428687608de"
      define_method(:install) do
        bin.install "ketch"
      end
    end
  end
end
