# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moxie < Formula
  desc "Chat agent service connecting Telegram and Slack to AI coding agents"
  homepage "https://github.com/1broseidon/moxie"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1broseidon/moxie/releases/download/v0.1.0/moxie_0.1.0_darwin_x86_64.tar.gz"
      sha256 "2eaa78af75ee632334eafcd621f68c7b09bf8101ae2097a7784e41e0ef88a2ef"

      define_method(:install) do
        bin.install "moxie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1broseidon/moxie/releases/download/v0.1.0/moxie_0.1.0_darwin_arm64.tar.gz"
      sha256 "d1f7be304e9c11aa209f60add112f6b01efbd7040530996b22960514c2370da7"

      define_method(:install) do
        bin.install "moxie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/moxie/releases/download/v0.1.0/moxie_0.1.0_linux_x86_64.tar.gz"
      sha256 "a7fa240991176d76f840337c63c684325f3475cac21e90bf88da8f1723cec7c7"
      define_method(:install) do
        bin.install "moxie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/moxie/releases/download/v0.1.0/moxie_0.1.0_linux_arm64.tar.gz"
      sha256 "a021bbe0e0a0f578df90a6070e573f189b200139434ab72420d864848b10015a"
      define_method(:install) do
        bin.install "moxie"
      end
    end
  end
end
