# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moxie < Formula
  desc "Chat agent service connecting Telegram and Slack to AI coding agents"
  homepage "https://github.com/1broseidon/moxie"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1broseidon/moxie/releases/download/v0.2.7/moxie_0.2.7_darwin_x86_64.tar.gz"
      sha256 "511fd5e9379933c4fa2d8265e07b8549e4748711a10522c4034ec73ba16447e8"

      define_method(:install) do
        bin.install "moxie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1broseidon/moxie/releases/download/v0.2.7/moxie_0.2.7_darwin_arm64.tar.gz"
      sha256 "51fb8a11f3f21db6c82f625bd30d6d5d3482dd387240756737b12fe117b1e783"

      define_method(:install) do
        bin.install "moxie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/moxie/releases/download/v0.2.7/moxie_0.2.7_linux_x86_64.tar.gz"
      sha256 "daa9404984c13b57e5da6474a33f89fdcfbdae3015abf9f18e2437d777b7d556"
      define_method(:install) do
        bin.install "moxie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/moxie/releases/download/v0.2.7/moxie_0.2.7_linux_arm64.tar.gz"
      sha256 "8abeecb1458bda1ffac3bcf70b62034ad459c1d2df6cdf86d06adb1f6c394cab"
      define_method(:install) do
        bin.install "moxie"
      end
    end
  end
end
