# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oa < Formula
  desc "Config-driven multi-agent CLI with a normalized interface"
  homepage "https://github.com/1broseidon/oneagent"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1broseidon/oneagent/releases/download/v0.12.0/oa_0.12.0_darwin_x86_64.tar.gz"
      sha256 "3079da51664cd9816cecee59d38e910e562f920e8e5440800f181e24a61ef796"

      define_method(:install) do
        bin.install "oa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1broseidon/oneagent/releases/download/v0.12.0/oa_0.12.0_darwin_arm64.tar.gz"
      sha256 "5b722ef2ca2dfd15977f6283bc45ab66b9ae6c4edfe6f6eba4587125ce93673f"

      define_method(:install) do
        bin.install "oa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/oneagent/releases/download/v0.12.0/oa_0.12.0_linux_x86_64.tar.gz"
      sha256 "f182d5d2dd6ab64676d12d09a5767d5b7d125d2fdcc7c285f0fd99fb0a92594f"
      define_method(:install) do
        bin.install "oa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/oneagent/releases/download/v0.12.0/oa_0.12.0_linux_arm64.tar.gz"
      sha256 "da8cb18f9705301b307fc8f8e7ed93f953d28095709ce21eec6dc2181f030e9f"
      define_method(:install) do
        bin.install "oa"
      end
    end
  end
end
