# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oa < Formula
  desc "Config-driven multi-agent CLI with a normalized interface"
  homepage "https://github.com/1broseidon/oneagent"
  version "0.11.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1broseidon/oneagent/releases/download/v0.11.10/oa_0.11.10_darwin_x86_64.tar.gz"
      sha256 "bf29e74adc0ed240f3898c36e7abd714ffc5f72af1a3fac9202c401099b5dc1a"

      define_method(:install) do
        bin.install "oa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1broseidon/oneagent/releases/download/v0.11.10/oa_0.11.10_darwin_arm64.tar.gz"
      sha256 "20fd5b869eddfea2bb0d1232fb3c0db7dc0280861def323101c0c2e52a5ebe3c"

      define_method(:install) do
        bin.install "oa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/oneagent/releases/download/v0.11.10/oa_0.11.10_linux_x86_64.tar.gz"
      sha256 "e4e7e5d608d01c614bda77608121ea67033bf911fdb6c6001b44cc974a46bfbd"
      define_method(:install) do
        bin.install "oa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/oneagent/releases/download/v0.11.10/oa_0.11.10_linux_arm64.tar.gz"
      sha256 "1db1bfd5805877c12803e6de45f2e5aac153e136a9d017c888d1d5a930af40d0"
      define_method(:install) do
        bin.install "oa"
      end
    end
  end
end
