# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Promptext < Formula
  desc "Smart code context extractor for AI assistants"
  homepage "https://promptext.sh"
  version "0.7.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1broseidon/promptext/releases/download/v0.7.5/promptext_Darwin_x86_64.tar.gz"
      sha256 "ff8d98d1903c57c39b70ffa06bd0ffc47b7f2675b18077a8ca0dca3b6c293347"

      define_method(:install) do
        bin.install "promptext"
        bin.install_symlink "promptext" => "prx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1broseidon/promptext/releases/download/v0.7.5/promptext_Darwin_arm64.tar.gz"
      sha256 "31ad3c7ad41f4d997f01efa2be7d33f8bbc63a3197102f0ef00ecf6b6fb9002c"

      define_method(:install) do
        bin.install "promptext"
        bin.install_symlink "promptext" => "prx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/promptext/releases/download/v0.7.5/promptext_Linux_x86_64.tar.gz"
      sha256 "74d65af2f3d587fed398bb325165477031012333b860283c0d584e4618c613c1"
      define_method(:install) do
        bin.install "promptext"
        bin.install_symlink "promptext" => "prx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/promptext/releases/download/v0.7.5/promptext_Linux_arm64.tar.gz"
      sha256 "6f44d6614d1c6be32ba31b8e85fa28a628bdc67bb1c597910e3dad2078420eef"
      define_method(:install) do
        bin.install "promptext"
        bin.install_symlink "promptext" => "prx"
      end
    end
  end
end
