# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Promptext < Formula
  desc "Smart code context extractor for AI assistants"
  homepage "https://promptext.sh"
  version "0.7.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1broseidon/promptext/releases/download/v0.7.4/promptext_Darwin_x86_64.tar.gz"
      sha256 "23e3a6eaf0316ea90df9995c6379c2b3ec2815d543cdd5d483ed6d5f109ea2d7"

      define_method(:install) do
        bin.install "promptext"
        bin.install_symlink "promptext" => "prx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1broseidon/promptext/releases/download/v0.7.4/promptext_Darwin_arm64.tar.gz"
      sha256 "cb7f03d9a14f1a14e6ab717a39bf79dc5f25403c6e5b4dca9095fe938f1623e1"

      define_method(:install) do
        bin.install "promptext"
        bin.install_symlink "promptext" => "prx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/promptext/releases/download/v0.7.4/promptext_Linux_x86_64.tar.gz"
      sha256 "6578a8a7e7f5bf184ed54162a2efa78a74163858c937cfa7efbfa4bf344c03e1"
      define_method(:install) do
        bin.install "promptext"
        bin.install_symlink "promptext" => "prx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1broseidon/promptext/releases/download/v0.7.4/promptext_Linux_arm64.tar.gz"
      sha256 "4125e77d310dc6cf85b6810b7197e5929778b058309b376148d74eb89f597078"
      define_method(:install) do
        bin.install "promptext"
        bin.install_symlink "promptext" => "prx"
      end
    end
  end
end
